export interface PhaseContent {
  phase: number;
  title: string;
  subtitle: string;
  paragraphs: string[];
  sources: string[];
}

export const phaseContent: PhaseContent[] = [
  {
    phase: 1,
    title: 'The Strike (February 28)',
    subtitle: 'How a surprise attack in 12 hours changed the Middle East',
    paragraphs: [
      'The February 28 strikes were not the beginning of the story. In June 2025, Israel and the United States had fought a shorter war against Iran that practically destroyed its air defense networks, significantly damaged its military-industrial complex, and struck nuclear infrastructure at Fordow, Natanz, and Isfahan. That campaign was declared a victory and ended without prolonged operations, on the assumption that the damage inflicted might be sufficient to destabilize the regime. When massive protests erupted across Iran in early 2026, driven by economic collapse and political repression, it appeared the strategy might work. But the regime cracked down with full force, killing between 3,000 and 30,000 people by various estimates. While the crackdown was still underway, President Trump promised the Iranian people: "Help is on the way." Carrier Strike Group 3, led by USS Abraham Lincoln, began moving to the Middle East.',
      'On February 28, 2026, the United States launched Operation Epic Fury and Israel launched Operation Roaring Lion. Roughly 900 strikes were executed within a 12-hour window, a tempo that exceeded the opening salvos of Desert Storm and left Iran\'s already-degraded air defenses overwhelmed before they could mount a coherent response.',
      'The leadership decapitation was devastating. Supreme Leader Ali Khamenei was killed along with IRGC Ground Forces Commander Mohammad Pakpour, Defense Minister Aziz Nasirzadeh, Chief of the Military Office Mohammad Shirazi, and dozens of other senior military and political leaders. Trump claimed 40 senior figures were killed. Senior clerical figure Ali Larijani was killed in a separate Israeli strike. Iran\'s constitutional succession mechanisms had never been tested under active military conflict, and Mojtaba Khamenei was named as the new Supreme Leader, though it remains unclear how much control he actually has. Nuclear facilities at Fordow, Natanz, and Isfahan sustained further damage from the combined June 2025 and February 2026 strikes, though Iran still possesses approximately 440 kilograms of enriched uranium, sufficient for roughly 10 nuclear weapons. One of the American strikes hit the Minab Girls\' Elementary School, killing more than 170 schoolgirls. The school had previously been an IRGC facility, meaning the strike was likely based on outdated intelligence.',
      'The stated aim of regime change represented a departure from decades of US declaratory policy, which had maintained that military action against Iran was aimed at preventing nuclear proliferation rather than altering its system of government. The legal and strategic justifications offered by the administration — that Khamenei\'s personal direction of terrorist proxies and the nuclear program made him a legitimate military target — were immediately contested by international law scholars and key allies. Whatever the legal merits, the operational reality of February 28 is now fixed: it marks the opening act of the first direct large-scale military conflict between the United States and Iran.',
    ],
    sources: [
      'US DoD Press Briefings, February 28 – March 2, 2026',
      'IAEA Emergency Board Statement, March 1, 2026',
      'Reuters/AP contemporaneous strike reporting, February 28, 2026',
      'Foreign Affairs: The Architecture of the February 28 Campaign',
    ],
  },
  {
    phase: 2,
    title: 'Retaliation & Escalation (Feb 28 – Mar 10)',
    subtitle: 'Iran\'s 500 missiles and the world\'s fastest escalation ladder',
    paragraphs: [
      'Iran\'s response, designated Operation True Promise IV, was neither measured nor delayed. Within hours of the initial strikes, Iran demonstrated that it had achieved at least some degree of decentralization in decision-making: even the death of the Supreme Leader and most military commanders did not prevent a strong response. The IRGC Aerospace Force launched more than 500 ballistic and cruise missiles at US military installations across Iraq, Qatar, Bahrain, and the UAE, accompanied by approximately 2,000 drones. Targets included Bahrain\'s capital Manama, the Saudi capital Riyadh, Abu Dhabi, and Kuwait International Airport. Iran chose an "if we burn, everyone burns" strategy, striking Gulf allies to increase the cost of war beyond just the US and Israel. The scale and simultaneity of this retaliation exceeded any previous Iranian missile salvo and demonstrated that survivable launch capacity had been preserved despite the initial strikes. Several US forward operating bases sustained significant damage; casualties among American servicemembers were in the dozens, triggering automatic escalation protocols under rules of engagement.',
      'The closure of the Strait of Hormuz, announced by acting Iranian military command on March 1, marked the escalation\'s transition from a military exchange to a global economic crisis. Iranian naval assets — including fast-attack craft, submarine-laid mines, and shore-based anti-ship missile batteries — enforced the blockade with sufficient credibility to halt commercial tanker transit within 24 hours of the declaration. Simultaneously, Hezbollah activated its full rocket and anti-tank missile arsenal against Israeli territory, opening a northern front that stretched Israeli air defenses and expanded the geographic scope of the conflict from the Persian Gulf to the eastern Mediterranean. The combination of the Hormuz closure and the Hezbollah activation transformed what had been conceived as a limited strike campaign into a multi-front regional war.',
      'By March 10 — twelve days after the initial strikes — the escalation ladder had been climbed to a level that strategists had long modeled as a worst-case scenario. Iran had struck the territory of four US-allied Gulf states; the United States had responded with sustained counter-battery operations against IRGC launch sites; Israel had struck Hezbollah command nodes in Lebanon and Syria; and the Strait of Hormuz remained closed to commercial navigation. Diplomatic off-ramps that had been theoretically available in the first 72 hours were foreclosed by the scale of casualties and the domestic political dynamics on all sides. The question shifted from whether full-scale war had begun to how long it would last and what it would cost.',
    ],
    sources: [
      'USCENTCOM Operations Update, March 1–10, 2026',
      'International Energy Agency Emergency Oil Market Assessment, March 3, 2026',
      'UN Secretary-General Statement on Hormuz Closure, March 2, 2026',
      'Institute for the Study of War: Iran Retaliation Campaign Tracker',
    ],
  },
  {
    phase: 3,
    title: 'Active Conflict (Current)',
    subtitle: 'Air supremacy, a paper ceasefire, and a blockade-on-blockade stand-off',
    paragraphs: [
      'As of April 24, 2026, the US-led air campaign has prosecuted strikes against more than 11,000 designated targets across Iran over 38 days of active combat. A two-week ceasefire mediated by Pakistan was announced on April 7-8, paused most strike operations, and has now been extended unilaterally by Trump on April 21 — hours before the April 22 expiration — at Pakistan\'s request. The extension is paper-thin. Within hours of the announcement, Iran\'s IRGC seized two container ships (the Italian-owned MSC Francesca and the Epaminondas) in the Strait of Hormuz. The ceasefire pauses air strikes on Iran but does not pause the wider war: a US naval blockade of Iranian ports has been in effect since April 13, ship seizures and counter-seizures continue, and on April 23 Trump ordered the US Navy to "shoot and kill" any Iranian boats laying mines in the strait. The April 6 deadline produced a ceasefire. The April 22 deadline produced a unilateral extension. The next deadline is whatever a single kinetic incident makes it.',
      'The air campaign achieved near-total air supremacy and degraded Iran\'s conventional military capacity to a degree not seen since the 2003 Iraq invasion. Approximately 300 to 400 strike sorties per day were sustained through early April, targeting nuclear infrastructure, IRGC military facilities, ballistic missile production and storage sites, air defense networks, and command nodes. The conflict expanded to a fourth front on March 28 when Houthi forces in Yemen formally declared war and launched a sustained barrage of ballistic missiles and attack drones at US naval assets in the Red Sea and at Gulf state infrastructure. The Houthi entry stretched US logistics and defensive capacity across four simultaneous theaters. Iran\'s missile capability declined sharply under attrition: after firing missiles in three-digit numbers on the first three days of the war, daily launches dropped to approximately 20-30 ballistic and cruise missiles. Israeli officials claimed 350 to 400 missile launchers were destroyed or disabled, with only 150 still active. Iranian drone swarms, typically 50-100 units per package, remained a major problem, with Gulf states forced to use expensive interceptors against cheap drones in a financially unsustainable cost exchange. On March 19, Iran hit an American F-35 fighter jet, confirmed by US Command as the first recorded instance of an F-35 being struck.',
      'Energy infrastructure became its own escalation rung: Iran struck the Shah gas fields of the UAE on March 9-10, Israel hit Iran\'s South Pars gas field on March 18, and Iran retaliated by damaging Qatar\'s Ras Laffan LNG facility. The fundamental question, however, has been answered: military dominance has not produced political compliance. Robert Pape\'s coercion theory predicted this with striking accuracy. The air campaign achieved ~100% tactical success but produced zero political concessions through the April 6 deadline, the 21-hour Islamabad talks on April 11-12, the April 22 ceasefire expiration, the Vance-led second Islamabad round on April 21 (which dissolved when Iran refused to attend), and the imposition of a US naval blockade. This is textbook Stage 2 of Pape\'s escalation trap: regime-change air campaign that produces tactical dominance but structural coercive failure, creating pressure for further escalation. The blockade is the escalation Pape\'s framework predicts. Russia\'s foreign minister Lavrov has now warned that the campaign will push Iran toward actually acquiring a nuclear weapon — the canonical "counterproductive" outcome where coercive pressure produces the very outcome it sought to prevent.',
    ],
    sources: [
      'Pentagon Press Briefings, February-April 2026',
      'CSIS Conflict Tracker: Iran Campaign, March-April 2026',
      'Reuters: US-Iran ceasefire agreed via Pakistan mediation, April 7, 2026',
      'NPR: US-Iran peace talks in Islamabad collapse, April 12, 2026',
      'CBS News: US Navy blockade of Iran takes effect, April 13, 2026',
      'TIME: Trump extends Iran ceasefire hours before expiration, April 21, 2026',
      'Al Jazeera: Trump orders Navy to "shoot and kill" Iranian mine-layers, April 23, 2026',
    ],
  },
  {
    phase: 4,
    title: 'Economic Shockwaves',
    subtitle: 'Brent at $106, Hormuz reopen pushed to H2 2026, dual blockade stand-off',
    paragraphs: [
      'The Strait of Hormuz closure, now in its eighth week, has produced what the International Energy Agency calls "the largest supply disruption in the history of the global oil market." Brent crude peaked near $120/bbl during the worst of the campaign and was trading around $106 on April 24, with WTI at $96. US gas prices hit $4 per gallon by March 31, a 30% surge driven directly by the conflict. Goldman Sachs and other Wall Street firms continue to model scenarios of $150 to $200 per barrel if the dual blockade hardens into open kinetic conflict in the strait. The IEA coordinated the largest Strategic Petroleum Reserve release in history, but reserve drawdowns are inherently time-limited and markets have priced in the structural constraint.',
      'The April 7 ceasefire required Iran to reopen the strait, and Iran did not. The April 17 brief reopening — when both Iran and the US claimed the strait was open and six cruise ships transited — collapsed within 24 hours when Iran shut the strait again on April 18, citing US "breaches of trust." On April 19 Iran\'s parliament moved to formalize a toll regime banning ships from "hostile" countries. The configuration is now a dual blockade: Iran blocks foreign shipping out of the strait, the US Navy blocks shipping into Iranian ports under Adm. Brad Cooper at CENTCOM, and Trump\'s April 23 order expanded scope so that no ship may enter or leave the strait without US Navy approval. As of April 24, ~80% of oil and gas executives surveyed by the Dallas Fed expect the strait will not fully reopen until August 2026 or later. Baker Hughes concurs. The reopen-by-summer assumption that priced into oil markets in early April is gone.',
      'Trump has told allies to "get your own oil" from Hormuz, and NATO allies have refused to participate in de-blockading operations, responding with what has become the refrain of this war: "This is not our war." The Trump administration temporarily suspended its embargo on Russian oil to mitigate the energy crisis, and Russia\'s foreign minister Lavrov met Chinese President Xi in Beijing in mid-April, with both governments describing the relationship as "unshakable amid any storms" — a visible hardening of the alternative supply axis that the blockade is consolidating. Beyond energy, Iranian strikes on desalination plants in the Gulf threaten the primary drinking water supply for Kuwait and Qatar, where desalinated water provides 99% of consumption. The GCC food emergency, already critical from Hormuz container disruption, is compounded by water risk. The World Food Programme estimates 40 million people in the broader region face acute food insecurity. South Asia and East Africa, dependent on Gulf remittances and re-exports, are experiencing cascading inflation spikes. Within the United States, energy producers enjoy windfall revenue while manufacturing and consumers absorb cost shocks — a political bifurcation that is now visible in polling on the war\'s domestic costs.',
    ],
    sources: [
      'International Energy Agency: Oil Market Report — Emergency Assessment, March-April 2026',
      'CNBC: Hormuz reopen pushed to H2 2026, Baker Hughes/Dallas Fed survey, April 24, 2026',
      'Bloomberg: Iran War — When Will the Strait of Hormuz Reopen?, April 21, 2026',
      'CNBC: Brent oil tops $105 as tensions simmer in Strait of Hormuz, April 23, 2026',
      'CNBC: Iran declares Strait of Hormuz open but Trump says blockade still active, April 17, 2026',
      'CNN: Iran says it is closing Strait of Hormuz again, April 18, 2026',
    ],
  },
  {
    phase: 5,
    title: 'Geopolitical Reactions',
    subtitle: 'A blockade nobody asked for, talks that collapsed twice, and an axis hardening',
    paragraphs: [
      'The United Nations Security Council passed Resolution 2817 on March 8, calling for an immediate ceasefire and the reopening of the Strait of Hormuz. Russia and China abstained rather than vetoing, both recognizing that the Hormuz closure affected their own economic interests. The resolution established an international consensus that neither side has honored in full. Iran expanded the geographic scope of the conflict by launching ballistic missiles at Turkey\'s Incirlik air base (US/NATO territory) and drones at Nakhchivan, Azerbaijan. NATO\'s response was muted, consistent with the alliance\'s posture throughout the war.',
      'Pakistan emerged as the primary mediator, displacing Turkey, and brokered the two-week ceasefire announced on April 7. The first round of direct US-Iran negotiations in Islamabad on April 11-12, led by VP Vance with Witkoff and Kushner facing Iran\'s Araghchi and Ghalibaf, ran for 21 hours before collapsing on the nuclear question. Vance said Iran refused to make "an affirmative commitment that they will not seek a nuclear weapon." Iran\'s parliament speaker Ghalibaf countered that the US "ultimately failed to gain the trust of the Iranian delegation" — a reference to Iran being bombed twice during prior negotiations. The structural gap is now public: the US wants a 20-year ban on Iranian uranium enrichment; Iran has offered five. On April 13, Trump imposed a US naval blockade on Iran. On April 21, hours before the April 22 ceasefire expiration, Trump unilaterally extended the ceasefire at Pakistan\'s request to give Iran time to assemble a "unified proposal." A Vance-led second Islamabad round was scheduled for the same day. It dissolved when Iran refused to attend.',
      'On April 22, hours after the ceasefire extension, Iran\'s IRGC seized two container ships — the Italian-owned MSC Francesca and the Epaminondas — in the Strait of Hormuz, having fired on three vessels. Panama, whose flag the MSC Francesca flies, denounced the seizure as a "grave attack against maritime security." On April 23, Trump ordered the US Navy to "shoot and kill" Iranian boats laying mines in the strait and expanded blockade scope so that no ship may enter or leave without US approval. Meanwhile, Russia\'s foreign minister Lavrov met Chinese President Xi in Beijing in mid-April; both governments described the relationship as "unshakable amid any storms." Lavrov publicly warned that the US-Israel campaign would push Iran toward actually acquiring a nuclear weapon — Pape\'s "counterproductive" outcome stated openly by a Permanent Five member. The Lebanon front remains contested: Pakistan\'s PM Sharif said the ceasefire covered Lebanon; Trump said it did not; France\'s Macron said it did; Israel\'s Netanyahu acted as if it did not, launching Operation Eternal Darkness on April 8 hours after the ceasefire was announced.',
    ],
    sources: [
      'UN Security Council Resolution 2817, March 8, 2026',
      'NPR: US-Iran peace talks in Islamabad collapse, April 12, 2026',
      'Washington Post: Trump announces naval blockade after Islamabad talks yield no deal, April 12, 2026',
      'NBC News / TIME: Trump extends Iran ceasefire hours before expiration, April 21, 2026',
      'Washington Post: Iran seizes 2 ships in Strait of Hormuz, April 22, 2026',
      'Al Jazeera: Why are the US, Iran arguing over duration of uranium enrichment ban?, April 14, 2026',
      'Washington Institute: Tracking Chinese and Russian Statements on the Iran War, April 2026',
    ],
  },
  {
    phase: 6,
    title: 'Humanitarian Impact',
    subtitle: 'Dead counted in thousands, Lebanon\'s worst week, and a public-health collapse',
    paragraphs: [
      'Casualty reporting has diverged. The International Federation of Red Cross and Red Crescent Societies reports at least 1,900 killed and ~20,000 injured in Iran from US-Israeli strikes as of early April. Human Rights Activists in Iran (HRANA), a US-based monitoring organization, has documented 3,636 war deaths through April 7, including 1,701 civilians, 1,221 military personnel, and 714 unclassified. HRANA notes that military counts are likely significant undercounts because confirmation depends on government data that the conflict has degraded. The dead include Iranian civilians killed in strikes on dual-use infrastructure, US and allied military personnel killed in Iran\'s retaliatory missile campaign, and civilians in Gulf states killed in IRGC drone and missile attacks. According to the Iranian Red Crescent, 307 health, medical, and emergency-care facilities had been damaged as of April 3. The UN Human Rights Office has opened investigations into specific strikes in Tehran, Isfahan, and Shiraz. The Minab Girls\' Elementary School strike, which killed more than 170 schoolgirls when the US hit a building that had previously been an IRGC facility using outdated intelligence, remains the most politically costly single incident of the war.',
      'The Lebanon front escalated catastrophically on April 8. Hours after the ceasefire between the US, Israel, and Iran was announced, and after Hezbollah signaled a pause in attacks, Israel launched Operation Eternal Darkness across Lebanon. One hundred airstrikes were executed within ten minutes by approximately fifty fighter jets dropping ~160 munitions, hitting central Beirut, southern Beirut suburbs, the port city of Sidon, the eastern Beqaa Valley, and the southern city of Tyre. At least 357 people were killed in a single day. The Lebanese Red Cross reported at least 300 killed or wounded in Beirut and surrounding areas. The 2026 Lebanon war has now killed more than 1,500 people and displaced nearly one million, roughly 20% of Lebanon\'s population. Netanyahu\'s office declared that Lebanon is not part of the ceasefire, despite Pakistan\'s and France\'s insistence that it is. The humanitarian crisis in Lebanon, compounding years of economic collapse and governance failure, is now one of the worst in the country\'s history.',
      'Beyond the direct killing, the infrastructure destruction across Iran and the Gulf has produced cascading public health crises. Iranian strikes on desalination plants in Kuwait and Qatar have threatened the primary drinking water supply for populations that depend on desalinated water for 99% of their consumption. Across 26 of Iran\'s 31 provinces, water treatment, power generation, and telecommunications have sustained damage producing waterborne disease outbreaks and hospital capacity at an estimated 40% of pre-conflict levels. The ICRC has described the health system as "approaching collapse." Cultural destruction is equally devastating: more than 120 UNESCO-listed and nationally significant historical sites have been damaged. Pape\'s empirical research on 33 air campaigns found that bombing consistently strengthens defender resolve rather than degrading it. The absence of mass anti-war protests inside Iran, the IRGC\'s threatened crackdown on dissent, and the confirmed rally-around-the-flag effect all validate Pape\'s nationalist backlash coefficient. Global anti-war demonstrations, the largest since the 2003 Iraq War protests, have drawn millions in European and American cities.',
    ],
    sources: [
      'IFRC: Iran casualty report, early April 2026 (~1,900 killed, ~20,000 injured)',
      'HRANA: Documented war deaths in Iran, April 7, 2026 (3,636 deaths including 1,701 civilians)',
      'Reuters / AP: Israel Operation Eternal Darkness kills 357 in Lebanon, April 8, 2026',
      'Amnesty International: Lebanon — urgent call to protect civilians, April 2026',
      'UN OCHA: Iran Conflict Humanitarian Situation Report, April 2026',
    ],
  },
  {
    phase: 7,
    title: 'Resolution Paths',
    subtitle: 'Blockade in effect, ships seized, "shoot and kill" in the strait',
    paragraphs: [
      'The April 22 ceasefire expiration came and went without producing the breakdown some expected, but also without producing peace. On April 21, hours before the deadline, Trump unilaterally extended the two-week ceasefire at Pakistan\'s request to give Iran time to assemble a "unified proposal." The Vance-led second Islamabad round, scheduled for the same day, dissolved when Iran refused to attend. On April 22, hours after the extension, Iran\'s IRGC seized two container ships in the Strait of Hormuz. On April 23, Trump ordered the US Navy to "shoot and kill" any Iranian boats laying mines in the strait. The ceasefire continues to exist on paper. The blockade does not — it is operational, expanding, and now structured so that no ship may enter or leave Hormuz without US Navy approval. Robert Pape\'s coercion theory predicted this trajectory with striking accuracy. His framework estimates that airpower coercion succeeds approximately 5% of the time against states employing asymmetric strategies. Through 38 days of air dominance, an April 6 deadline, an April 7 ceasefire, an April 12 talks collapse, an April 13 blockade, an April 22 deadline, and the April 21 cancellation of Islamabad-2, Iran has produced zero substantive concessions on the nuclear question. This is textbook coercive failure: maximum military pressure, minimum political result. Pape further estimates a 75% probability that air-only coercion failure leads to escalation. The blockade is that escalation. Russia\'s Lavrov has now publicly argued the campaign will push Iran toward acquiring a bomb — Pape\'s "counterproductive" outcome stated by a Permanent Five member.',
      'The power vacuum created by Khamenei\'s death remains the wildcard. Iran\'s constitutional succession mechanisms have never been tested under conditions of active military conflict and leadership decapitation. The Assembly of Experts has been unable to convene in full. Acting authority has devolved to a committee of IRGC commanders and surviving government officials. The Islamabad negotiations revealed that Iran\'s political structure can produce a negotiating delegation: Foreign Minister Araghchi and Parliament Speaker Ghalibaf represented a functional if fragmented government. But the delegation did not have authority to commit Iran to forgoing nuclear weapons. The cancellation of Islamabad-2 — Iran simply refusing to send a team — suggests internal alignment has tightened around refusal rather than fragmenting toward concession. Iran\'s parliament moving on April 19 to formalize a Hormuz toll regime points the same direction: institutionalizing the leverage rather than trading it away.',
      'The resolution paths have hardened. First: a frozen conflict in which the unilaterally-extended ceasefire continues to be extended in two-week increments, the dual blockade persists, kinetic incidents in the strait remain contained below the threshold of full hostilities resumption, and the conflict ages into a Korea-style stand-off. This is now the modal path. Second: the wider regional war, in which a single kinetic miscalculation in Hormuz (a US Navy strike on an Iranian boat that turns out to be a fishing vessel; a successful Iranian attack on a US naval asset; an Israeli operation in Lebanon that draws Hezbollah into resumed strikes on US forces) produces a cascade. The probability of this path has risen materially with the "shoot and kill" order. Third: ground operations, which still face the same severe geographic constraints — Zagros Mountains, no staging base, amphibious-only approach. Limited island operations (Kharg, Qeshm) or a coastal foothold to break the Hormuz closure remain the maximum the US appears prepared to attempt. Fourth: a negotiated settlement, which requires Iran to accept a 20-year enrichment ban it has refused (offering five), and the US to accept terms it has called "excessive" when Iran proposed sanctions relief, frozen-asset release, Hormuz toll rights, and an end to Israel\'s Lebanon operations. The gap is structural and the trust required to bridge it has been further degraded by the blockade and the collapse of Islamabad-2.',
    ],
    sources: [
      'NPR: US-Iran peace talks in Islamabad collapse, April 12, 2026',
      'CBS News: US Navy blockade of Iran takes effect, April 13, 2026',
      'NBC News / TIME: Trump extends Iran ceasefire hours before expiration, April 21, 2026',
      'NPR / CNBC / Washington Post: Iran seizes 2 ships in Strait of Hormuz, April 22, 2026',
      'Al Jazeera / Euronews: Trump orders Navy to "shoot and kill" Iranian mine-layers, April 23, 2026',
      'Pape, Bombing to Win: Air Power and Coercion in War (Cornell, 1996)',
    ],
  },
  {
    phase: 8,
    title: 'Long-Term Aftermath',
    subtitle: 'Nuclear futures, regime survival, and the post-American Middle East',
    paragraphs: [
      'The April events answered one question and posed another. The question answered: Iran will not voluntarily give up its nuclear program under military pressure. The Islamabad talks collapsed on April 12 over Iran\'s refusal to commit to forgoing nuclear weapons; the second Islamabad round dissolved on April 21 when Iran refused to attend. The structural gap is now public — the US wants a 20-year ban on uranium enrichment; Iran has offered five. Iran still possesses approximately 440 kilograms of enriched uranium, sufficient for roughly 10 nuclear weapons, and the February 28 strikes damaged but did not permanently destroy enrichment capacity. The question posed: what happens to the global nonproliferation order when a state is bombed, blockaded, and pressured for nearly two months — through ceasefire, talks, talk collapse, and counter-blockade — and still does not concede on the nuclear question? Russia\'s foreign minister Lavrov has stated explicitly that the campaign will push Iran toward acquiring a bomb. Pape predicted this. Other states will draw the lesson that nuclear weapons capability is the only reliable deterrent against regime change. This is already being discussed in Riyadh, Ankara, and Seoul.',
      'The regional order is more unstable than before the war. Lebanon, where Israel launched Operation Eternal Darkness during a ceasefire, has suffered more than 1,500 killed and nearly one million displaced. Iraq faces renewed political fragmentation from strikes on IRGC-linked militias. The Houthi consolidation of control in Yemen has been accelerated by their entry into the conflict. The Arab-Israeli normalization architecture has been set back by years. The US naval blockade, in effect since April 13, has produced a strategic contradiction that no American adversary has failed to notice: the United States is simultaneously blockading Iran and attempting to break Iran\'s blockade of Hormuz, with the consequence that Hormuz reopen consensus has slipped to H2 2026 and the IEA now characterizes the closure as the "largest supply disruption in the history of the global oil market." Russia\'s Lavrov met China\'s Xi in Beijing in mid-April; both governments described their relationship as "unshakable amid any storms" — a visible hardening of the alternative-supply axis that the blockade is consolidating. China, with $300 billion in annual Hormuz-connected trade, has moved from quiet back-channel pressure to overt calls for an immediate end to hostilities.',
      'Iran has been devastated and will take decades to recover. But the regime will likely survive. The Islamabad negotiations demonstrated that Iran\'s post-Khamenei government can function diplomatically. The cancellation of Islamabad-2 demonstrated that it can also choose not to. The ideology and governing system, backed by millions of supporters including armed ones, remain intact. No wartime protests have emerged. The IRGC has threatened crackdown on any dissent, and the rally-around-the-flag effect is confirmed by the absence of mass opposition during active bombardment. Trump can claim victory and exit the war whenever he chooses, but the failure to bring the regime down, the failure to secure nuclear concessions despite 38 days of bombing, the failure to effectively protect Gulf allies, the failure to break the Hormuz closure even with a counter-blockade, and the visible hardening of the Russia-China-Iran axis all constitute strategic costs that will be weighed against the tactical destruction achieved. The fiscal burden, preliminary DoD estimates exceeding $180 billion, arrives on top of an already-strained federal balance sheet. Indo-Pacific military planners have raised formal concerns about the diversion of precision munitions, naval assets, and ISR capacity at a moment of elevated Taiwan Strait tension. The administration\'s argument that permanent elimination of a near-nuclear Iranian state justifies these costs will be tested against events in the months and years ahead. As of today, Iran has not been denuclearized, has explicitly refused to be, and now has a Permanent Five member arguing publicly that it should arm itself.',
    ],
    sources: [
      'NPR: US-Iran peace talks in Islamabad collapse, April 12, 2026',
      'CBS News: US Navy blockade of Iran takes effect, April 13, 2026',
      'Washington Institute: Tracking Chinese and Russian Statements on the Iran War, April 2026',
      'Al Jazeera: Lavrov warns Iran war could push Tehran toward nuclear bomb, March-April 2026',
      'Carnegie Endowment: Nuclear Proliferation After Iran — Regional Cascades, April 2026',
      'RAND Corporation: Strategic Costs of the Iran Campaign for Indo-Pacific Posture, April 2026',
    ],
  },
];

export function getPhaseContent(phase: number): PhaseContent | undefined {
  return phaseContent.find((p) => p.phase === phase);
}
